public protocol ChildOfAny {}

extension HtmlPlaintext: ChildOfAny {}
extension HtmlRawtext: ChildOfAny {}
extension HtmlComment: ChildOfAny {}

extension Array: ChildOfAny where Element: ChildOfAny {}
extension Either: ChildOfAny where Left: ChildOfAny, Right: ChildOfAny {}
extension EmptyView: ChildOfAny {}
extension AnyView: ChildOfAny {}
extension Optional: ChildOfAny where Wrapped: ChildOfAny {}
extension ModifiedContent: ChildOfAny {}

extension HtmlA: ChildOfAny {}
extension HtmlAbbr: ChildOfAny {}
extension HtmlAddress: ChildOfAny {}
extension HtmlArticle: ChildOfAny {}
extension HtmlAside: ChildOfAny {}
extension HtmlAudio: ChildOfAny {}
extension HtmlB: ChildOfAny {}
extension HtmlBdi: ChildOfAny {}
extension HtmlBdo: ChildOfAny {}
extension HtmlBlockquote: ChildOfAny {}
extension HtmlBr: ChildOfAny {}
extension HtmlButton: ChildOfAny {}
extension HtmlCanvas: ChildOfAny {}
extension HtmlCite: ChildOfAny {}
extension HtmlCode: ChildOfAny {}
extension HtmlDel: ChildOfAny {}
extension HtmlDetails: ChildOfAny {}
extension HtmlDfn: ChildOfAny {}
extension HtmlDiv: ChildOfAny {}
extension HtmlDl: ChildOfAny {}
extension HtmlEm: ChildOfAny {}
extension HtmlFieldset: ChildOfAny {}
extension HtmlFigure: ChildOfAny {}
extension HtmlFooter: ChildOfAny {}
extension HtmlForm: ChildOfAny {}
extension HtmlH1: ChildOfAny {}
extension HtmlH2: ChildOfAny {}
extension HtmlH3: ChildOfAny {}
extension HtmlH4: ChildOfAny {}
extension HtmlH5: ChildOfAny {}
extension HtmlH6: ChildOfAny {}
extension HtmlHeader: ChildOfAny {}
extension HtmlHr: ChildOfAny {}
extension HtmlI: ChildOfAny {}
extension HtmlIframe: ChildOfAny {}
extension HtmlImg: ChildOfAny {}
extension HtmlInput: ChildOfAny {}
extension HtmlIns: ChildOfAny {}
extension HtmlKbd: ChildOfAny {}
extension HtmlLabel: ChildOfAny {}
extension HtmlMain: ChildOfAny {}
extension HtmlMap: ChildOfAny {}
extension HtmlMark: ChildOfAny {}
extension HtmlMeter: ChildOfAny {}
extension HtmlNav: ChildOfAny {}
extension HtmlNoscript: ChildOfAny {}
extension HtmlObject: ChildOfAny {}
extension HtmlOl: ChildOfAny {}
extension HtmlOptgroup: ChildOfAny {}
extension HtmlOutput: ChildOfAny {}
extension HtmlP: ChildOfAny {}
extension HtmlPicture: ChildOfAny {}
extension HtmlPre: ChildOfAny {}
extension HtmlProgress: ChildOfAny {}
extension HtmlQ: ChildOfAny {}
extension HtmlS: ChildOfAny {}
extension HtmlSamp: ChildOfAny {}
extension HtmlScript: ChildOfAny {}
extension HtmlSection: ChildOfAny {}
extension HtmlSelect: ChildOfAny {}
extension HtmlSmall: ChildOfAny {}
extension HtmlSpan: ChildOfAny {}
extension HtmlStrong: ChildOfAny {}
extension HtmlSub: ChildOfAny {}
extension HtmlSup: ChildOfAny {}
extension HtmlSvg: ChildOfAny {}
extension HtmlTable: ChildOfAny {}
extension HtmlTemplate: ChildOfAny {}
extension HtmlTextarea: ChildOfAny {}
extension HtmlTime: ChildOfAny {}
extension HtmlU: ChildOfAny {}
extension HtmlUl: ChildOfAny {}
extension HtmlVar: ChildOfAny {}
extension HtmlVideo: ChildOfAny {}
